Feature/op 126
BitBagCommerce/SyliusProductBundlePlugin pull request #40
Opened 2023-03-22 11:52 UTC by rafalmal

2023-03-27 07:36 UTC, senghe commented
Threads that follow the upgrade topic:

https://github.com/BitBagCommerce/SyliusProductBundlePlugin/pull/39
https://github.com/BitBagCommerce/SyliusProductBundlePlugin/issues/38

2023-03-28 15:13 UTC, senghe requested changes

2023-04-04 13:52 UTC, jakublech commented
Not much left on this PR. Can you tak a look? It is important, awaited upgrade.

2023-04-04 19:32 UTC, senghe commented on composer.json
> +        "symfony/web-profiler-bundle": "^5.4 || ^6.0",
Yup i know @jakublech. Just saw a 4.4 mention in composer.json, so asked about this. But now it's OK.

2023-04-04 19:36 UTC, senghe commented on tests/Application/config/api_resources/Product.xml
> +<?xml version="1.0" ?>
@rafalmal if it's needed, please tell me why - I'm wondering. And if it's necessary, please update the README installation docs to include that files.

2023-04-05 04:51 UTC, rafalmal commented on tests/Application/config/api_resources/Product.xml
> +<?xml version="1.0" ?>
This API resources was located in src/Resources/api_resources earlier, but in sylius 1.12 they stopped beeing imported so i have moved them up in directory tree

2023-04-06 11:45 UTC, senghe approved these changes

2023-04-06 11:45 UTC, merged