Sylius 2.0 upgrade
BitBagCommerce/SyliusProductBundlePlugin pull request #57
Opened 2024-10-07 12:23 UTC by JanPalen

Upgrade plugin to Sylius 2.0.

- Change dependencies
- Fix tests/Application for new Sylius version
- Fix for Symfony 7

2025-01-14 07:58 UTC, senghe requested changes

2025-01-14 07:58 UTC, senghe commented on phpstan.neon.dist
> +        - '/Parameter #1 \$productRepository of method BitBag\\SyliusProductBundlePlugin\\Component\\Product\\AddToCartFormComponent::initializeProduct\(\) expects Sylius\\Component\\Core\\Repository
Do we really need so many errors ignored? Can't we handle them?

2025-01-14 07:58 UTC, senghe commented on src/Component/Product/AddToCartFormComponent.php
> +    //TODO there should be decoration instead of extension ? To discuss
Should this todo be handled?

2025-01-14 07:58 UTC, senghe commented on src/Component/Product/AddToCartFormComponent.php
> +    public function __construct(
Could you write any spec for this class?

2025-01-14 07:58 UTC, senghe commented on src/Handler/Api/AddProductBundleToCartHandler.php
> +    public function __invoke(AddProductBundleToCartDto $addProductBundleToCartCommand): OrderInterface
Could you write some specs for this class?

2025-01-14 07:58 UTC, senghe commented on src/Handler/Api/AddProductBundleToCartHandler.php
> +final class AddProductBundleToCartHandler
I do not get, why this is written from scratch. Was this feature missing?

2025-01-14 07:58 UTC, senghe commented on tests/Api/Responses/admin/get_product_bundle_collection_response.json
> +      "@id": "\/api\/v2/admin\/product-bundles\/@integer@",
Why only one backslash has been removed?

2025-01-14 07:58 UTC, senghe commented on tests/Api/Responses/shop/get_order_with_bundle_response.json
> +      "variant": "/api/v2/shop/product-variants/@string@",
So the "productBundleItems" is "hidden" here, am I right?

2025-01-14 07:58 UTC, senghe commented on tests/Application/assets/admin/entry.js
> +import 'sylius/bundle/AdminBundle/Resources/assets/entrypoint';
Is this any standard?

2025-01-14 09:08 UTC, JanPalen commented on src/Component/Product/AddToCartFormComponent.php
> +    //TODO there should be decoration instead of extension ? To discuss
From my point of view extension is the correct way. Maybe you have different point of view?

2025-01-14 09:17 UTC, JanPalen commented on src/Handler/Api/AddProductBundleToCartHandler.php
> +final class AddProductBundleToCartHandler
It is some bug in git for me. That file existed from 2019 and I just edited that.

2025-01-14 09:19 UTC, JanPalen commented on tests/Api/Responses/shop/get_order_with_bundle_response.json
> +      "variant": "/api/v2/shop/product-variants/@string@",
My missclick

2025-01-14 09:19 UTC, JanPalen commented on tests/Api/Responses/admin/get_product_bundle_collection_response.json
> +      "@id": "\/api\/v2/admin\/product-bundles\/@integer@",
Missclick

2025-01-14 09:20 UTC, JanPalen commented on tests/Api/Responses/shop/get_order_with_bundle_response.json
> +      "variant": "/api/v2/shop/product-variants/@string@",
Yes you are right.

2025-01-14 09:24 UTC, JanPalen commented on tests/Application/assets/admin/entry.js
> +import 'sylius/bundle/AdminBundle/Resources/assets/entrypoint';
Thats how sylius 2.0 need to do that

2025-01-14 10:25 UTC, JanPalen commented on phpstan.neon.dist
> +        - '/Parameter #1 \$productRepository of method BitBag\\SyliusProductBundlePlugin\\Component\\Product\\AddToCartFormComponent::initializeProduct\(\) expects Sylius\\Component\\Core\\Repository
I handled some of them.

2025-01-15 11:57 UTC, senghe commented on src/Component/Product/AddToCartFormComponent.php
> +    //TODO there should be decoration instead of extension ? To discuss
I do not have any preference, just wanted to highlight the comment

2025-01-15 11:58 UTC, senghe approved these changes
@JanPalen please remove the TODO comment, and we can go with testing on branch

2025-01-19 19:58 UTC, merged